Resolved "error C2229: class 'PlayerSpec' has an illegal zero-sized array" NOTE: change class PlayerSpec for TBC and Classic
Missing include for VERSION_STRING